on: ["push", "pull_request"]

name: Coveralls Tests

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      strategy:
        matrix:
          node-version: [10.x, 12.x, 14.x]
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm ci, run tests
      run: |
        npm ci
        npm run test

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}